### ISSUE TITLE
Link preferences menu

### ISSUE THREAD

**Issue by jurassicplayer** [jurassicplayer/rhythmbox-radio-record#10]
Shoddy preference menu made in Glade, just need to link everything and figure out how to make it show up.

**Comment by fossfreedom** [comment]
can you point me to where in the code you are having an issue - together with a description of what you are trying to achieve.  Happy to try to help you.

**Comment by jurassicplayer** [comment]
I can't figure out how to add a preferences window to the "Preferences" button in the plugin manager. I have a preferences.ui that has the signals connected and it seems to work (currently it's in the "Tools" menu so I could test it). The plugins that I've looked at seem to all have an rb3 compatibility bit that I must be getting lost in because I can't find where it gets bound to the Preferences button.

In the code:
Pretty much I need something like from lines 276-283, where you bind the Preferences button to a method, that I could put at line 323.

**Comment by fossfreedom** [comment]
To enable the preferences button in the plugin manager you must create a separate class inherited from PeasGtk.Configurable.

e.g.
-  class Preferences(GObject.Object, PeasGtk.Configurable)

Override  do_create_configure_widget - this must return the link to the container that will be displayed within the preferences window.

See line 111 from my preferences window: https://github.com/fossfreedom/alternative-toolbar/blob/master/alttoolbar_preferences.py

Since you are just using one module just create the class within this module.  If you create a separate python module,  you'll need to import that Preferences class from your main module.

Hope that helps.

**Comment by jurassicplayer** [comment]
Thanks~! I didn't know I needed to create a whole class with PeasGtk.Configurable. I was able to get a working preferences menu to show up in the plugin manager.
